### ISSUE TITLE
Colors change with LSP

### ISSUE THREAD

**Issue by jsongerber** [loctvl842/monokai-pro.nvim#80] opened 2023-09-11 19:23 UTC
Hi, 

When LSP is done loading with typescript using tsserver, the colors changes (see screen recording).
Variable colors which were white become purple, and interface colors also changes.

I think it may be related to semantic tokens, but I'm not sure.

https://github.com/loctvl842/monokai-pro.nvim/assets/18051702/6e6e9948-e451-4c35-a0a3-20fa6d49a84d

Also, should export statement be red?
Anyway, nice theme! Thanks

**Comment by loctvl842** [comment] 2023-09-12 05:11
Indeed, the colors are derived from semantic tokens and Treesitter. Since Treesitter loads first, and semantic tokens load afterward, this sequence of loading results in a change in colors.

**Comment by jsongerber** [comment] 2023-09-12 08:09
Thank you for your fast response.
Shouldn't variables stay white or is there a reason for it to become another color?
If this is intended behavior I'll close the issue

**Comment by loctvl842** [comment] 2023-09-13 02:54
> Thank you for your fast response.
Shouldn't variables stay white or is there a reason for it to become another color?
If this is intended behavior I'll close the issue

If variable is constant, it will use magenta color. Thanks for using it.

**Closed** 2023-09-13 10:19 UTC
